


```{r setup, echo= FALSE, message=FALSE,warning= FALSE}

# Strings ain't factors
options(stringsAsFactors = FALSE)

# Load the required libraries
library(knitr)
library(xtable)
library(RODBC)
library(plyr)
library(ggplot2)
library(scales)
library(gridExtra)
library(lubridate)
library(reshape2)


# Set default chunk options
opts_chunk$set(echo = FALSE,
               results = 'asis',
               message = FALSE,
               warning = FALSE,
               fig.width = 10,
               error = TRUE)


# Source the data.frame pretty-printer
source("..//fun//dfprint.r")


# Set period dates
# Go twelve weeks back from the next Monday - this helps ensure that
# plotted weeks are full weeks. Otherwise, you might end up with just a Friday,
# which makes a given week look really slow.
source("..//fun//get_prior_monday.r")
start_date <- get_prior_monday(Sys.Date(), weeks.back = 12)
stop_date <- Sys.Date()


# Set some default plot parameters
point_size <- 3
line_size <- 1.3
colorwheel <- c("#31A354", "#ADDD8E", "#F03B20", "#43A2CA")

theme_tb <- theme_bw() +
            theme(legend.key.width = unit(.75, "inches"))



# Set up the database connection
if(interactive()) { 
    plus <- odbcConnect("tbdbplus64")
    dbconnect <- "tbdbplus64"
} else {
    plus <- odbcConnect("tbdbplus32")
    dbconnect <- "tbdbplus32"
}




```






# TB Clinic Daily Status Report
Updated at `r paste(Sys.time())`

---------------------------------

## Recent Clinic Visits

```{r visits}


source("../Quarterly Strategic Area Review//R//fun/query_visits.r")

visits <- query_visits(start_date = start_date,
                       stop_date = stop_date,
                       odbc = dbconnect)

# Add a week indicator
visits$visit_week <- format(visits$visit_date, format = "%Y-%W")

# Aggregate by week
locagg <- ddply(subset(visits, location %in% c("Clinic", "Outreach")),
                .var = c("location", "visit_week"),
                .fun = summarise,
                n_visits = length(visit_date),
                week_date = get_prior_monday(as.Date(max(visit_date, na.rm = TRUE)))
)


totals <- ddply(subset(visits, location %in% c("Clinic", "Outreach")),
                .var = "visit_week",
                .fun = summarise,
                n_visits = length(visit_date),
                week_date = get_prior_monday(as.Date(max(visit_date, na.rm = TRUE)))
)


totals$location <- "All Visits"

visitagg <- rbind(locagg, totals)



ggplot(visitagg, aes(x = week_date, y = n_visits, group = location, color = location)) +
    geom_point(size = point_size) +
    geom_line(aes(linetype = location), size = line_size) +
    expand_limits(y = 0) +
    scale_x_date(breaks = date_breaks("1 week")) +
    scale_color_manual("Visit Location", values = colorwheel[1:3]) +
    scale_linetype_discrete("Visit Location") +
    labs(x = "Visit Week", 
         y = "Number of visits",
         title = "Patient Visits by Location") +
    theme_tb + theme(axis.text.x = element_text(angle = 70, hjust = 1.30, vjust = 1.3))



```


```{r, results='asis'}

# Cast visits wide
visits_wide <- dcast(visitagg, week_date ~ location, value.var = "n_visits")

# Pretty-print
names(visits_wide) <- c("Visit Week", "Total Visits", "Clinic Visits", "Outreach Visits")

dfprint(visits_wide)

```


-------------------------------------------
## Recent Screenings
```{r screens}

# Load the function
source("../Quarterly Strategic Area Review//R//fun/query_tests.r")

# Query test results for the period
tests <- query_tests(start_date = start_date,
                     stop_date = stop_date,
                       odbc = dbconnect)


# Add a week indicator
tests$test_week <- format(tests$test_date, format = "%Y-%W")


# Aggregate by week
testagg <- ddply(tests,
                .var = c("test", "test_week"),
                .fun = summarise,
                freq = length(test_date),
                week_date = get_prior_monday(as.Date(max(test_date, na.rm = TRUE)))
)


# Plot it
ggplot(testagg, aes(x = week_date, y = freq, group = test, color = test)) +
    geom_point(size = point_size) +
    geom_line(aes(linetype = test), size = line_size) +
    expand_limits(y = 0) +
    scale_x_date(breaks = date_breaks("1 week")) +
    scale_color_manual("Diagnostic", values = colorwheel[1:3]) +
    scale_linetype_discrete("Diagnostic") +
    labs(x = "Diagnostic date", 
         y = "Number of diagnostics",
         title = "Screenings for Active and Latent Tuberculosis") +
    theme_tb + theme(axis.text.x = element_text(angle = 70, hjust = 1.30, vjust = 1.3))


```


```{r, results='asis'}

# Cast tests wide
tests_wide <- dcast(testagg, week_date ~ test, value.var = "freq")

# Pretty-print
names(tests_wide) <- c("Test Week", "CXRs", "QFTs", "TSTs")

dfprint(tests_wide)

```



## Current Contact Investigations

```{r investigations}

# Summarize the open contact investigations
investigations <- sqlQuery(plus, "
                           
    SELECT c.person_id, d.last_name, d.first_name,
           c.date_opened, c.reason_for, c.priority, c.lead_investigator
    FROM Contact_Investigation c LEFT OUTER JOIN Demos_View d
    ON c.person_id = d.person_id
    WHERE c.status = 'Open'
                           
")

# Summarize the contacts themselves
contacts <- sqlQuery(plus, "
  
    SELECT source_person_id, contact_person_id, priority, contact_status
    FROM Contact
                     
")

contact_sum <- ddply(contacts, .var = "source_person_id", .fun = summarise,
                     n_contacts = length(contact_person_id),
                     n_open = sum(contact_status %in% 1, na.rm = TRUE),
                     priority_one = sum(priority %in% 3, na.rm = TRUE),
                     priority_two = sum(priority %in% 2, na.rm = TRUE),
                     priority_three = sum(priority %in% 1, na.rm = TRUE)
)


# Merge contact info onto investigation info
invest_sum <- merge(x = investigations,
                    y = contact_sum,
                    by.x = "person_id",
                    by.y = "source_person_id",
                    all.x = TRUE)


# Convert it all to character for better printing
invest_print <- data.frame(lapply(invest_sum, as.character))

dfprint(arrange(invest_print, lead_investigator, date_opened))

```



## Patients currently receiving treatment for Active TB
```{r active_tx}

# Query open active treatment plans
act_plans <- sqlQuery(plus, "
                      
    SELECT t.person_id, d.last_name, d.first_name, 
           t.treat_plan, t.treat_plan_date, t.plan_author,
           t.latest_tx, t.n_tx_completed
    FROM Tx_Plan_View t LEFT OUTER JOIN Demos_view d
    ON t.person_id = d.person_id
    WHERE treat_plan_type = 'Active'
        AND plan_status = 'Open'
        AND author_affiliation = 'Denver Metro TB Clinic'
        AND treat_plan_date > #2009-01-01#
                      
")

dfprint(arrange(act_plans, plan_author, latest_tx))


```



## Upcoming DOTs (Next Three Days)
```{r upcoming_dots}

# Query DOTs coming up in the next week
dots <- sqlQuery(plus, "
                 
    SELECT t.person_id, d.last_name, d.first_name, t.treatment_date
    FROM Drug_Treatment t LEFT OUTER JOIN Demos_View d
    ON t.person_id = d.person_id
    WHERE dispense_type IN ('DOT', 'DOPT')
        AND t.treatment_date >= Date()
        AND t.treatment_date <= Date() + 3
                 
")

dfprint(arrange(dots, treatment_date, person_id))

```


## Upcoming LTBI Pickups (Next Seven Days)
```{r upcoming_pickups}

# Query pickups coming up in the next week
pickups <- sqlQuery(plus, "
                 
    SELECT t.person_id, d.last_name, d.first_name, t.treatment_date
    FROM Drug_Treatment t LEFT OUTER JOIN Demos_View d
    ON t.person_id = d.person_id
    WHERE dispense_type = 'Pickup'
        AND t.treatment_date >= Date()
        AND t.treatment_date <= Date() + 7
                 
")

dfprint(arrange(pickups, treatment_date))

```



## CXRs Awaiting Action
```{r action_cxrs}

# Query the CXRs with action required from TBdb
action_cxrs <- sqlQuery(plus, "
    
    SELECT x.person_id, x.cxr_date_taken, x.cxr_date_read,
           x.cxr_action_text, x.action_required
    FROM CXR_View x LEFT OUTER JOIN TB_Case c
    ON x.person_id = c.person_id
    WHERE c.agency_id = 30
        AND (x.action_required = 'Yes' OR x.action_required Is Null)
    ORDER BY x.cxr_action_text, x.cxr_date_taken
                         
")

# Convert cxr_date_taken to Date
action_cxrs$cxr_date_taken <- as.Date(action_cxrs$cxr_date_taken)

# There are a lot of CXRs with action_required = NA; we only need to address
# those in the last year
action_cxrs_recent <- subset(action_cxrs,
                             subset = action_required %in% "Yes" |
                                      (is.na(action_cxrs$action_required) & 
                                      action_cxrs$cxr_date_taken >= (Sys.Date() - 365)),
                             select = !names(action_cxrs) %in% "action_required"
)

dfprint(action_cxrs_recent)


```







```{r cleanup}

# Close the database connection
odbcClose(plus)


```




